import os
from pathlib import Path

SEED = 1337

DATA_PATH = os.path.join(Path(os.path.abspath(__file__)).parent.parent.parent, "data")

training_file_name = "training.jsonl"
validation_file_name = "validation.jsonl"

DEFAULT_COMPANY_BINS = [
	{
		"bin": "Entertainment & Media",
		"companies": ["AskPlayStation", "GooglePlayMusic", "JackBox", "SpotifyCares", "XboxSupport", "hulu_support"],
		"keywords": [
			"film",
			"television",
			"music",
			"digital media",
			"gaming",
			"broadcasting",
			"streaming",
			"content creation",
			"advertising",
			"publishing",
		],
	},
	{
		"bin": "Finance & Banking",
		"companies": [
			"AskAmex",
			"AskCiti",
			"AskPayPal",
			"AskRBC",
			"AskRobinhood",
			"AskVirginMoney",
			"Ask_WellsFargo",
			"BofA_Help",
			"ChaseSupport",
		],
		"keywords": [
			"banking",
			"investments",
			"loans",
			"financial services",
			"insurance",
			"mortgages",
			"credit unions",
			"financial markets",
			"asset management",
			"risk management",
		],
	},
	{
		"bin": "Telecommunications",
		"companies": [
			"ATT",
			"Ask_Spectrum",
			"CenturyLinkHelp",
			"CoxHelp",
			"O2",
			"Safaricom_Care",
			"TMobileHelp",
			"USCellularCares",
			"VerizonSupport",
			"airtel_care",
			"comcastcares",
			"sprintcare",
		],
		"keywords": [
			"mobile networks",
			"wireless communication",
			"broadband internet",
			"fiber optics",
			"satellite communication",
			"telephony",
			"5G technology",
			"VoIP",
			"network infrastructure",
			"data transmission",
		],
	},
	{
		"bin": "Travel & Hospitality",
		"companies": [
			"AirAsiaSupport",
			"AirbnbHelp",
			"AlaskaAir",
			"AmericanAir",
			"AskLyft",
			"British_Airways",
			"Delta",
			"HiltonHelp",
			"IHGService",
			"JetBlue",
			"Kimpton",
			"LondonMidland",
			"SouthwestAir",
			"Uber_Support",
			"VirginAmerica",
			"VirginAtlantic",
			"VirginTrains",
			"nationalrailenq",
		],
		"keywords": [
			"travel",
			"hospitality",
			"tourism",
			"accommodation",
			"airlines",
			"hotels",
			"travel agencies",
			"customer experience",
			"tour operators",
			"cultural exchange",
		],
	},
	{
		"bin": "Technology & Software",
		"companies": [
			"ATVIAssist",
			"AWSSupport",
			"AdobeCare",
			"AppleSupport",
			"AskDSC",
			"AskSeagate",
			"AskTigogh",
			"AzureSupport",
			"DellCares",
			"DropboxSupport",
			"GoDaddyHelp",
			"HPSupport",
			"MicrosoftHelps",
			"NortonSupport",
			"OfficeSupport",
			"PandoraSupport",
			"SCsupport",
			"SW_Help",
			"TwitterSupport",
			"YahooCare",
			"asksalesforce",
			"mediatemplehelp",
			"sizehelpteam",
		],
		"keywords": [
			"software development",
			"cloud computing",
			"artificial intelligence",
			"cybersecurity",
			"IT services",
			"machine learning",
			"big data",
			"mobile applications",
			"SaaS",
			"tech innovation",
		],
	},
	{
		"bin": "Retail & Food Services",
		"companies": [
			"AldiUK",
			"AmazonHelp",
			"ArbysCares",
			"ArgosHelpers",
			"AskPapaJohns",
			"AskTarget",
			"AskeBay",
			"ChipotleTweets",
			"DoorDash_Help",
			"DunkinDonuts",
			"GreggsOfficial",
			"KFC_UKI_Help",
			"MOO",
			"McDonalds",
			"Morrisons",
			"NeweggService",
			"NikeSupport",
			"Postmates_Help",
			"TacoBellTeam",
			"Tesco",
			"Walmart",
			"askpanera",
			"marksandspencer",
			"sainsburys",
		],
		"keywords": [
			"retail",
			"food services",
			"consumer goods",
			"restaurants",
			"grocery stores",
			"hospitality",
			"e-commerce",
			"logistics",
			"supply chain",
			"customer experience",
		],
	},
	{
		"bin": "Healthcare & Pharmaceuticals",
		"companies": ["AsurionCares", "BoostCare", "GWRHelp", "GloCare", "MTNC_Care", "VMUcare", "idea_cares"],
		"keywords": [
			"biotechnology",
			"pharmaceuticals",
			"medical devices",
			"healthcare services",
			"public health",
			"clinical trials",
			"patient care",
			"health insurance",
			"telemedicine",
			"regulations",
		],
	},
	{
		"bin": "Transportation & Logistics",
		"companies": ["TfL", "UPSHelp"],
		"keywords": [
			"supply chain",
			"freight",
			"shipping",
			"warehousing",
			"logistics management",
			"transportation",
			"inventory control",
			"last-mile delivery",
			"distribution",
			"trucking",
		],
	},
	{"bin": "None", "companies": [], "description": "No specific industry bin identified.", "keywords": []},
]

DEFAULT_COMPANY_BINS_WITHOUT_COMPANIES = [{"bin": bin["bin"], "keywords": bin["keywords"]} for bin in DEFAULT_COMPANY_BINS]

training_file_path = os.path.join(DATA_PATH, training_file_name)
validation_file_path = os.path.join(DATA_PATH, validation_file_name)
