import os
from pathlib import Path

SEED = 1337

DATA_PATH = os.path.join(Path(os.path.abspath(__file__)).parent.parent.parent, "data")

training_file_name = "training.jsonl"
validation_file_name = "validation.jsonl"

DEFAULT_COMPANY_BINS = [
	{
		"bin": "Aerospace & Transportation",
		"keywords": [
			"flights",
			"airlines",
			"boarding",
			"check-in",
			"passengers",
			"travel",
			"delays",
			"luggage",
			"reservations",
			"connections",
			"airport",
			"tickets",
			"cruise",
			"routes",
			"customer service",
		],
		"companies": [
			"AmericanAir",
			"Delta",
			"SouthwestAir",
			"British_Airways",
			"JetBlue",
			"AlaskaAir",
			"VirginAmerica",
			"VirginAtlantic",
			"AirAsiaSupport",
		],
	},
	{
		"bin": "Retail & E-commerce",
		"keywords": [
			"shopping",
			"cart",
			"checkout",
			"discount",
			"delivery",
			"returns",
			"offers",
			"inventory",
			"promotions",
			"sales",
			"online shopping",
			"price",
			"marketplace",
			"customer feedback",
			"store locator",
		],
		"companies": [
			"AmazonHelp",
			"Walmart",
			"eBay",
			"AldiUK",
			"Tesco",
			"Sainsburys",
			"ArgosHelpers",
			"MarksandSpencer",
			"DoorDash_Help",
			"McDonalds",
			"TacoBellTeam",
			"ChipotleTweets",
			"Panera",
			"GreggsOfficial",
			"KFC_UKI_Help",
		],
	},
	{
		"bin": "Technology & Software",
		"keywords": [
			"software",
			"applications",
			"updates",
			"features",
			"bug fixes",
			"cloud",
			"security",
			"data",
			"network",
			"user experience",
			"integration",
			"deployment",
			"AI",
			"support",
			"analytics",
		],
		"companies": [
			"AdobeCare",
			"MicrosoftHelps",
			"DropboxSupport",
			"GoDaddyHelp",
			"AppleSupport",
			"AWSSupport",
			"NortonSupport",
			"OfficeSupport",
			"AzureSupport",
			"XboxSupport",
			"HPSupport",
			"AskSalesforce",
			"Idea_Cares",
			"Mediatemplehelp",
		],
	},
	{
		"bin": "Food & Beverage",
		"keywords": [
			"menu",
			"ingredients",
			"nutrition",
			"restaurant",
			"takeout",
			"meal delivery",
			"ordering",
			"customer favorites",
			"specials",
			"appetizers",
			"drinks",
			"franchise",
			"seasonal items",
			"promotions",
			"feedback",
		],
		"companies": [
			"DunkinDonuts",
			"ArbysCares",
			"ChipotleTweets",
			"KFC_UKI_Help",
			"TacoBellTeam",
			"McDonalds",
			"JackBox",
			"GreggsOfficial",
			"Panera",
		],
	},
	{
		"bin": "Telecommunications",
		"keywords": [
			"network coverage",
			"data plans",
			"mobile devices",
			"customer service",
			"billing",
			"sim card",
			"technical support",
			"installation",
			"service outage",
			"upgrades",
			"contracts",
			"family plans",
			"international services",
			"support tickets",
			"issues",
			"hardware",
		],
		"companies": ["ATT", "VerizonSupport", "TMobileHelp", "SprintCare", "O2", "USCellularCares", "CenturyLinkHelp", "ComcastCares"],
	},
	{
		"bin": "Hospitality & Travel",
		"keywords": [
			"bookings",
			"reservations",
			"amenities",
			"check-in",
			"customer reviews",
			"packages",
			"concierge",
			"events",
			"dining",
			"experience",
			"partnership",
			"transportation",
			"relaxation",
			"feedback",
			"customer satisfaction",
		],
		"companies": ["AirbnbHelp", "HiltonHelp", "Kimpton", "IHGService", "LondonMidland", "Uber_Support"],
	},
	{"bin": "None"},
]

training_file_path = os.path.join(DATA_PATH, training_file_name)
validation_file_path = os.path.join(DATA_PATH, validation_file_name)
