import os
from pathlib import Path

SEED = 1337

DATA_PATH = os.path.join(Path(os.path.abspath(__file__)).parent.parent.parent, "data")

training_file_name = "training.jsonl"
validation_file_name = "validation.jsonl"

DEFAULT_COMPANY_BINS = [
	{
		"bin": "Entertainment & Media",
		"companies": ["AskPlayStation", "GooglePlayMusic", "JackBox", "XboxSupport", "hulu_support", "SpotifyCares"],
		"keywords": [
			"film",
			"music",
			"television",
			"streaming",
			"gaming",
			"content creation",
			"advertising",
			"media distribution",
			"digital platforms",
			"live performances",
		],
	},
	{
		"bin": "Finance & Banking",
		"companies": [
			"Ask_WellsFargo",
			"AskRBC",
			"AskVirginMoney",
			"ChaseSupport",
			"AskCiti",
			"AskPayPal",
			"BofA_Help",
			"AskRobinhood",
			"AskAmex",
		],
		"keywords": [
			"investment",
			"lending",
			"accounting",
			"risk management",
			"credit analysis",
			"financial planning",
			"banking regulations",
			"capital markets",
			"portfolio management",
			"wealth management",
		],
	},
	{
		"bin": "Telecommunications",
		"companies": [
			"VerizonSupport",
			"ATT",
			"Ask_Spectrum",
			"USCellularCares",
			"sprintcare",
			"comcastcares",
			"TMobileHelp",
			"O2",
			"CenturyLinkHelp",
			"Safaricom_Care",
			"CoxHelp",
			"airtel_care",
		],
		"keywords": [
			"5G",
			"broadband",
			"mobile networks",
			"telecom infrastructure",
			"wireless communications",
			"signal transmission",
			"fiber optics",
			"VoIP",
			"satellite communication",
			"network security",
		],
	},
	{
		"bin": "Travel & Hospitality",
		"companies": [
			"IHGService",
			"AmericanAir",
			"AirbnbHelp",
			"VirginAtlantic",
			"AirAsiaSupport",
			"British_Airways",
			"HiltonHelp",
			"Kimpton",
		],
		"keywords": [
			"accommodation",
			"tourism",
			"booking",
			"destinations",
			"travel packages",
			"hospitality services",
			"customer experience",
			"transportation",
			"adventure travel",
			"sustainable tourism",
		],
	},
	{
		"bin": "Technology & Software",
		"companies": [
			"DropboxSupport",
			"AskTigogh",
			"DellCares",
			"AWSSupport",
			"MicrosoftHelps",
			"NortonSupport",
			"asksalesforce",
			"AdobeCare",
			"AskSeagate",
			"HPSupport",
			"SCsupport",
			"AppleSupport",
			"AzureSupport",
			"PandoraSupport",
			"sizehelpteam",
			"GoDaddyHelp",
			"AskDSC",
			"OfficeSupport",
			"mediatemplehelp",
			"SW_Help",
			"ATVIAssist",
			"TwitterSupport",
		],
		"keywords": [
			"software development",
			"cloud computing",
			"artificial intelligence",
			"machine learning",
			"cybersecurity",
			"data analytics",
			"mobile applications",
			"internet of things",
			"blockchain",
			"agile methodologies",
		],
	},
	{
		"bin": "Retail & Food Services",
		"companies": [
			"ChipotleTweets",
			"DunkinDonuts",
			"Tesco",
			"ArbysCares",
			"sainsburys",
			"TacoBellTeam",
			"AskPapaJohns",
			"NeweggService",
			"marksandspencer",
			"NikeSupport",
			"AldiUK",
			"AskeBay",
			"AmazonHelp",
			"GreggsOfficial",
			"McDonalds",
			"Morrisons",
			"KFC_UKI_Help",
			"Walmart",
			"askpanera",
			"AskTarget",
		],
		"keywords": [
			"consumer behavior",
			"supply chain management",
			"inventory control",
			"e-commerce",
			"customer experience",
			"point of sale (POS)",
			"merchandising",
			"food safety",
			"branding",
			"market trends",
		],
	},
	{
		"bin": "Healthcare & Pharmaceuticals",
		"companies": ["GWRHelp", "idea_cares", "VMUcare", "BoostCare", "GloCare", "AsurionCares", "YahooCare", "MTNC_Care"],
		"keywords": [
			"medication",
			"clinical trials",
			"patient care",
			"pharmaceutical research",
			"healthcare systems",
			"biotechnology",
			"medical devices",
			"regulatory compliance",
			"telemedicine",
			"public health",
		],
	},
	{
		"bin": "Transportation & Logistics",
		"companies": [
			"Uber_Support",
			"TfL",
			"nationalrailenq",
			"LondonMidland",
			"UPSHelp",
			"Postmates_Help",
			"AskLyft",
			"Delta",
			"ArgosHelpers",
			"AlaskaAir",
			"MOO",
			"DoorDash_Help",
			"SouthwestAir",
			"VirginAmerica",
			"JetBlue",
			"VirginTrains",
		],
		"keywords": [
			"supply chain management",
			"freight forwarding",
			"logistics optimization",
			"transportation management",
			"last-mile delivery",
			"warehousing",
			"shipping",
			"fleet management",
			"inventory control",
			"global trade",
		],
	},
	{"bin": "None", "companies": [], "keywords": []},
]

DEFAULT_COMPANY_BINS_WITHOUT_COMPANIES = [{"bin": bin["bin"], "keywords": bin["keywords"]} for bin in DEFAULT_COMPANY_BINS]

training_file_path = os.path.join(DATA_PATH, training_file_name)
validation_file_path = os.path.join(DATA_PATH, validation_file_name)
